site_name: GM
site_description: GraphicsMagick and ImageMagick for node
site_author: Nosy
copyright: '版权 &copy; 2017 - 2018 wohugb.github.io'

# Repository
repo_name: wohugb/gm
repo_url: https://github.com/wohugb/gm
edit_uri: ""

theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"
  extra_css: [assets/stylesheets/extra.css]
# Customization
extra:
  social:
    - type: globe
      link: http://wohugb.github.io
    - type: github-alt
      link: https://github.com/wohugb
    - type: twitter
      link: https://twitter.com/wohugb
    - type: linkedin
      link: https://linkedin.com/in/wohugb

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

# Page tree
pages:
  - 概述: index.md
  - 基础用法: BasicUsage.md
  - 流: Streams.md
  - 缓冲区: Buffers.md
  - 蒙太奇: Montage.md
  - 自定义:
      - 参数: custom/arguments.md
      - 标识格式字符串: custom/IdentifyFormatString.md
  - 方法: Manipulation.md
  - 获取器: Getters.md
  - 绘画: 
    - 命令: drawing/index.md
    - 举例: drawing/example.md
  - 合成:
    - 概述: composite/index.md
    - 代码: composite/example.md
  - 比较: ImageComparisons.md
  - 使用IM: UsingImagemagick.md
  - 扩展: Extending.md
  - GM:
    - 概述: GraphicsMagick/index.md
    - 下载: GraphicsMagick/Download.md
    - 安装: GraphicsMagick/Install.md
    - 工具: GraphicsMagick/Utilities.md
    - 手册: 
      - 主页: GraphicsMagick/Manual/index.md
      - 动画: GraphicsMagick/Manual/animate.md
      - 批量: GraphicsMagick/Manual/batch.md
      - 基准: GraphicsMagick/Manual/benchmark.md
      - 比较: GraphicsMagick/Manual/compare.md
      - 合并: GraphicsMagick/Manual/composite.md
      - 魔术: GraphicsMagick/Manual/conjure.md
      - 转换: GraphicsMagick/Manual/convert.md
      - 显示: GraphicsMagick/Manual/display.md
      - 识别: GraphicsMagick/Manual/identify.md
      - 导入: GraphicsMagick/Manual/import.md
      - mogrify: GraphicsMagick/Manual/mogrify.md
      - 蒙太奇: GraphicsMagick/Manual/montage.md
      - 时间: GraphicsMagick/Manual/time.md
      - 版本: GraphicsMagick/Manual/version.md
    - FAQ: GraphicsMagick/FAQ.md

